### ISSUE TITLE
Crumbs defined in Route Config Do Not Show If App Refresh / Direct Access of URL

### ISSUE THREAD

**Issue by stevehaneytrailblazer** [henczi/ngx-crumbs#1]
I am really liking your library but one quirk I've noticed is that if I define crumbs in routing config they work great when the app has already loaded and navigate around but if I directly access one of the URLs or hit Refresh on that browser page the breadcrumbs don't seem to render at all.

If I use component based crumbs they seem to load in both scenarios.  So I've been using that pattern for now.  Just wanted to ask if you've seen this behavior or maybe I am missing some configuration.

Thanks.

**Comment by henczi** [comment]
Hi @stevehaneytrailblazer 

I was not able to reproduce the bug.
Please provide a link to a repo or Stackblitz that can reproduce the issue you described.

**Comment by stevehaneytrailblazer** [comment]
I was trying to recreate and its a little tricky to do so in close approximation but I can't just port my code over as-is.  I also couldn't recreate on stackblitz so I'm gonna try to break down my steps a little more.  Apologies for entering an issue before trying the stackblitz.  We can close this.
